export type Role = "SUPER_ADMIN" | "ORG_ADMIN" | "ANALYST" | "VIEWER";
export type OfferingType = "PRODUCT"|"SERVICE"|"PLAN"|"SUBSCRIPTION"|"SAAS_PLAN"|"ROOM"|"HOTEL_ROOM"|"RENTAL"|"COURSE"|"PACKAGE"|"LISTING"|"BOOKING"|"BUNDLE"|"SKU_BUNDLE"|"CUSTOM";
export type JobStatus = "PENDING"|"RUNNING"|"COMPLETED"|"FAILED"|"CANCELLED";
export type AlertType = "PRICE_CHANGE"|"PERCENTAGE_DROP"|"UNDERCUT_THRESHOLD"|"STOCK_CHANGE"|"CIRCUIT_BREAKER_TRIPPED";

export interface User { id:string; client_id:string; email:string; full_name:string; role:Role; is_active:boolean; last_login_at?:string|null; created_at:string; updated_at:string; client?:Client|null }
export interface Client { id:string; name:string; slug:string; company_name?:string|null; country?:string|null; timezone?:string|null; default_currency?:string|null; default_market?:string|null; industry?:string|null; account_preferences?:Record<string,unknown>|null; status:string; created_at:string; updated_at:string }
export interface AuthResponse { access_token:string; refresh_token?:string|null; token_type:string; expires_in:number; user:User }
export interface Competitor { id:string; client_id:string; name:string; domain:string; status:string; created_at:string; updated_at:string }
export interface SourceConfig { id:string; source_id:string; rate_limit_rpm:number; request_delay_seconds:number; timeout_seconds:number; max_retries:number; user_agent_strategy:string; requires_proxy:boolean; requires_javascript:boolean; custom_headers:Record<string,unknown>; extraction_selectors:Record<string,unknown>; created_at:string }
export interface Source { id:string; competitor_id:string; name:string; base_url:string; source_type:string; collection_method:string; verification_status:string; circuit_state:string; failure_count:number; consecutive_successes:number; circuit_opened_at?:string|null; circuit_half_opened_at?:string|null; health_status:string; is_active:boolean; created_at:string; updated_at:string; configuration?:SourceConfig|null }
export interface Offering { id:string; client_id:string; name:string; offering_type:OfferingType; custom_type_name?:string|null; sku?:string|null; current_price?:string|number|null; currency?:string|null; market:string; url?:string|null; category?:string|null; image_url?:string|null; description?:string|null; attributes:Record<string,unknown>; is_archived:boolean; is_monitored:boolean; created_via:string; created_at:string; updated_at:string }
export interface Match { id:string; offering_id:string; source_id:string; target_url:string; match_status:string; confidence_score:number; extraction_selectors?:Record<string,unknown>|null; is_active:boolean; created_at:string; updated_at:string }
export interface OfferingDetail extends Offering { competitor_matches_count:number; min_competitor_price?:string|number|null; avg_competitor_price?:string|number|null; price_delta_percent?:string|number|null; matches:Array<Record<string,unknown>> }
export interface Pagination<T> { items:T[]; total_count:number; page:number; page_size:number; total_pages:number; has_more:boolean }
export interface Job { id:string; source_id:string; job_type:string; status:JobStatus; started_at?:string|null; completed_at?:string|null; total_items_processed:number; successful_items:number; failed_items:number; error_category?:string|null; error_message?:string|null; meta_info:Record<string,unknown>; created_at:string }
export interface DiscoveryJob { job_id:string; client_id:string; target_url:string; status:JobStatus; total_pages_crawled:number; total_items_processed:number; successful_items:number; failed_items:number; error_message?:string|null; created_offerings_count:number; updated_offerings_count:number; items:Array<Record<string,unknown>>; started_at?:string|null; completed_at?:string|null }
export interface AlertRule { id:string; client_id:string; offering_id?:string|null; name:string; alert_type:AlertType; threshold_value?:number|null; target_channels:Record<string,unknown>; is_active:boolean; cooldown_minutes:number; last_triggered_at?:string|null; created_at:string; updated_at:string }
export interface DynamicFieldDefinition { id:string; client_id:string; field_name:string; display_name:string; data_type:string; unit?:string|null; category?:string|null; description?:string|null; is_selected:boolean; confidence:string; is_required:boolean; is_comparable:boolean; options?:Record<string,unknown>|null; created_at:string }
export interface AlertLog { id:string; alert_rule_id:string; offering_match_id?:string|null; title:string; message:string; triggered_value?:string|number|null; payload_snapshot:Record<string,unknown>; is_read:boolean; created_at:string }
